review:
  auto_review: true
  base_branches:
  - main
  - develop
  ignore_patterns:
  - "*.md"
  - "*.json"
  - "*.yml"
  summary:
    bullet_points: 5
  commit_message: true
  sequence_diagrams: true
  ci_patches: true
  inline_code_suggestions: true
  tools: [ trivy, "your-custom-tool" ]

chat: {}

language: "en"
temperature: 0.2
