reviews:
  profile: chill
  sequence_diagrams: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    base_branches:
    - main
    - develop
  tools:
    gitleaks:
      enabled: true

chat: {}

language: "en"
temperature: 0.2
